name = "iot"
main = "src/index.js"
compatibility_date = "2024-06-03"

# D1 databases section MUST be an array of tables in newer Wrangler versions
[[d1_databases]]
binding = "dataiot"
database_name = "iotbase"
# NOTE: The database_id MUST be correct for your 'iotbase' database.
# Based on your previous screenshots, this ID is correct:
database_id = "06d4d2a7-f235-43a9-b36d-556b27d5440c"

# Compatibility Flags for Node.js features (Replaces deprecated node_compat = true)
[compatibility_flags]
nodejs_compat = true
